// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package github

import (
	"context"
	"sync"
)

// Ensure, that GitHubClientMock does implement ClientInterface.
// If this is not the case, regenerate this file with moq.
var _ ClientInterface = &GitHubClientMock{}

// GitHubClientMock is a mock implementation of ClientInterface.
//
//	func TestSomethingThatUsesClientInterface(t *testing.T) {
//
//		// make and configure a mocked ClientInterface
//		mockedClientInterface := &GitHubClientMock{
//			GetJobLogsFunc: func(ctx context.Context, repo string, jobID int64) (string, error) {
//				panic("mock out the GetJobLogs method")
//			},
//			GetPRMetadataFunc: func(ctx context.Context, prURLOrNumber string, repo string) (*PRMetadata, error) {
//				panic("mock out the GetPRMetadata method")
//			},
//			GetPRStatusFunc: func(ctx context.Context, prURL string) (*PRStatus, error) {
//				panic("mock out the GetPRStatus method")
//			},
//			PostPRCommentFunc: func(ctx context.Context, prURL string, body string) error {
//				panic("mock out the PostPRComment method")
//			},
//			PostReplyToCommentFunc: func(ctx context.Context, prURL string, commentID int, body string) error {
//				panic("mock out the PostReplyToComment method")
//			},
//			PostReviewReplyFunc: func(ctx context.Context, prURL string, reviewCommentID int, body string) error {
//				panic("mock out the PostReviewReply method")
//			},
//			ResolveReviewThreadFunc: func(ctx context.Context, prURL string, commentID int) error {
//				panic("mock out the ResolveReviewThread method")
//			},
//		}
//
//		// use mockedClientInterface in code that requires ClientInterface
//		// and then make assertions.
//
//	}
type GitHubClientMock struct {
	// GetJobLogsFunc mocks the GetJobLogs method.
	GetJobLogsFunc func(ctx context.Context, repo string, jobID int64) (string, error)

	// GetPRMetadataFunc mocks the GetPRMetadata method.
	GetPRMetadataFunc func(ctx context.Context, prURLOrNumber string, repo string) (*PRMetadata, error)

	// GetPRStatusFunc mocks the GetPRStatus method.
	GetPRStatusFunc func(ctx context.Context, prURL string) (*PRStatus, error)

	// PostPRCommentFunc mocks the PostPRComment method.
	PostPRCommentFunc func(ctx context.Context, prURL string, body string) error

	// PostReplyToCommentFunc mocks the PostReplyToComment method.
	PostReplyToCommentFunc func(ctx context.Context, prURL string, commentID int, body string) error

	// PostReviewReplyFunc mocks the PostReviewReply method.
	PostReviewReplyFunc func(ctx context.Context, prURL string, reviewCommentID int, body string) error

	// ResolveReviewThreadFunc mocks the ResolveReviewThread method.
	ResolveReviewThreadFunc func(ctx context.Context, prURL string, commentID int) error

	// calls tracks calls to the methods.
	calls struct {
		// GetJobLogs holds details about calls to the GetJobLogs method.
		GetJobLogs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// JobID is the jobID argument value.
			JobID int64
		}
		// GetPRMetadata holds details about calls to the GetPRMetadata method.
		GetPRMetadata []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrURLOrNumber is the prURLOrNumber argument value.
			PrURLOrNumber string
			// Repo is the repo argument value.
			Repo string
		}
		// GetPRStatus holds details about calls to the GetPRStatus method.
		GetPRStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrURL is the prURL argument value.
			PrURL string
		}
		// PostPRComment holds details about calls to the PostPRComment method.
		PostPRComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrURL is the prURL argument value.
			PrURL string
			// Body is the body argument value.
			Body string
		}
		// PostReplyToComment holds details about calls to the PostReplyToComment method.
		PostReplyToComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrURL is the prURL argument value.
			PrURL string
			// CommentID is the commentID argument value.
			CommentID int
			// Body is the body argument value.
			Body string
		}
		// PostReviewReply holds details about calls to the PostReviewReply method.
		PostReviewReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrURL is the prURL argument value.
			PrURL string
			// ReviewCommentID is the reviewCommentID argument value.
			ReviewCommentID int
			// Body is the body argument value.
			Body string
		}
		// ResolveReviewThread holds details about calls to the ResolveReviewThread method.
		ResolveReviewThread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrURL is the prURL argument value.
			PrURL string
			// CommentID is the commentID argument value.
			CommentID int
		}
	}
	lockGetJobLogs          sync.RWMutex
	lockGetPRMetadata       sync.RWMutex
	lockGetPRStatus         sync.RWMutex
	lockPostPRComment       sync.RWMutex
	lockPostReplyToComment  sync.RWMutex
	lockPostReviewReply     sync.RWMutex
	lockResolveReviewThread sync.RWMutex
}

// GetJobLogs calls GetJobLogsFunc.
func (mock *GitHubClientMock) GetJobLogs(ctx context.Context, repo string, jobID int64) (string, error) {
	callInfo := struct {
		Ctx   context.Context
		Repo  string
		JobID int64
	}{
		Ctx:   ctx,
		Repo:  repo,
		JobID: jobID,
	}
	mock.lockGetJobLogs.Lock()
	mock.calls.GetJobLogs = append(mock.calls.GetJobLogs, callInfo)
	mock.lockGetJobLogs.Unlock()
	if mock.GetJobLogsFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.GetJobLogsFunc(ctx, repo, jobID)
}

// GetJobLogsCalls gets all the calls that were made to GetJobLogs.
// Check the length with:
//
//	len(mockedClientInterface.GetJobLogsCalls())
func (mock *GitHubClientMock) GetJobLogsCalls() []struct {
	Ctx   context.Context
	Repo  string
	JobID int64
} {
	var calls []struct {
		Ctx   context.Context
		Repo  string
		JobID int64
	}
	mock.lockGetJobLogs.RLock()
	calls = mock.calls.GetJobLogs
	mock.lockGetJobLogs.RUnlock()
	return calls
}

// GetPRMetadata calls GetPRMetadataFunc.
func (mock *GitHubClientMock) GetPRMetadata(ctx context.Context, prURLOrNumber string, repo string) (*PRMetadata, error) {
	callInfo := struct {
		Ctx           context.Context
		PrURLOrNumber string
		Repo          string
	}{
		Ctx:           ctx,
		PrURLOrNumber: prURLOrNumber,
		Repo:          repo,
	}
	mock.lockGetPRMetadata.Lock()
	mock.calls.GetPRMetadata = append(mock.calls.GetPRMetadata, callInfo)
	mock.lockGetPRMetadata.Unlock()
	if mock.GetPRMetadataFunc == nil {
		var (
			pRMetadataOut *PRMetadata
			errOut        error
		)
		return pRMetadataOut, errOut
	}
	return mock.GetPRMetadataFunc(ctx, prURLOrNumber, repo)
}

// GetPRMetadataCalls gets all the calls that were made to GetPRMetadata.
// Check the length with:
//
//	len(mockedClientInterface.GetPRMetadataCalls())
func (mock *GitHubClientMock) GetPRMetadataCalls() []struct {
	Ctx           context.Context
	PrURLOrNumber string
	Repo          string
} {
	var calls []struct {
		Ctx           context.Context
		PrURLOrNumber string
		Repo          string
	}
	mock.lockGetPRMetadata.RLock()
	calls = mock.calls.GetPRMetadata
	mock.lockGetPRMetadata.RUnlock()
	return calls
}

// GetPRStatus calls GetPRStatusFunc.
func (mock *GitHubClientMock) GetPRStatus(ctx context.Context, prURL string) (*PRStatus, error) {
	callInfo := struct {
		Ctx   context.Context
		PrURL string
	}{
		Ctx:   ctx,
		PrURL: prURL,
	}
	mock.lockGetPRStatus.Lock()
	mock.calls.GetPRStatus = append(mock.calls.GetPRStatus, callInfo)
	mock.lockGetPRStatus.Unlock()
	if mock.GetPRStatusFunc == nil {
		var (
			pRStatusOut *PRStatus
			errOut      error
		)
		return pRStatusOut, errOut
	}
	return mock.GetPRStatusFunc(ctx, prURL)
}

// GetPRStatusCalls gets all the calls that were made to GetPRStatus.
// Check the length with:
//
//	len(mockedClientInterface.GetPRStatusCalls())
func (mock *GitHubClientMock) GetPRStatusCalls() []struct {
	Ctx   context.Context
	PrURL string
} {
	var calls []struct {
		Ctx   context.Context
		PrURL string
	}
	mock.lockGetPRStatus.RLock()
	calls = mock.calls.GetPRStatus
	mock.lockGetPRStatus.RUnlock()
	return calls
}

// PostPRComment calls PostPRCommentFunc.
func (mock *GitHubClientMock) PostPRComment(ctx context.Context, prURL string, body string) error {
	callInfo := struct {
		Ctx   context.Context
		PrURL string
		Body  string
	}{
		Ctx:   ctx,
		PrURL: prURL,
		Body:  body,
	}
	mock.lockPostPRComment.Lock()
	mock.calls.PostPRComment = append(mock.calls.PostPRComment, callInfo)
	mock.lockPostPRComment.Unlock()
	if mock.PostPRCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PostPRCommentFunc(ctx, prURL, body)
}

// PostPRCommentCalls gets all the calls that were made to PostPRComment.
// Check the length with:
//
//	len(mockedClientInterface.PostPRCommentCalls())
func (mock *GitHubClientMock) PostPRCommentCalls() []struct {
	Ctx   context.Context
	PrURL string
	Body  string
} {
	var calls []struct {
		Ctx   context.Context
		PrURL string
		Body  string
	}
	mock.lockPostPRComment.RLock()
	calls = mock.calls.PostPRComment
	mock.lockPostPRComment.RUnlock()
	return calls
}

// PostReplyToComment calls PostReplyToCommentFunc.
func (mock *GitHubClientMock) PostReplyToComment(ctx context.Context, prURL string, commentID int, body string) error {
	callInfo := struct {
		Ctx       context.Context
		PrURL     string
		CommentID int
		Body      string
	}{
		Ctx:       ctx,
		PrURL:     prURL,
		CommentID: commentID,
		Body:      body,
	}
	mock.lockPostReplyToComment.Lock()
	mock.calls.PostReplyToComment = append(mock.calls.PostReplyToComment, callInfo)
	mock.lockPostReplyToComment.Unlock()
	if mock.PostReplyToCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PostReplyToCommentFunc(ctx, prURL, commentID, body)
}

// PostReplyToCommentCalls gets all the calls that were made to PostReplyToComment.
// Check the length with:
//
//	len(mockedClientInterface.PostReplyToCommentCalls())
func (mock *GitHubClientMock) PostReplyToCommentCalls() []struct {
	Ctx       context.Context
	PrURL     string
	CommentID int
	Body      string
} {
	var calls []struct {
		Ctx       context.Context
		PrURL     string
		CommentID int
		Body      string
	}
	mock.lockPostReplyToComment.RLock()
	calls = mock.calls.PostReplyToComment
	mock.lockPostReplyToComment.RUnlock()
	return calls
}

// PostReviewReply calls PostReviewReplyFunc.
func (mock *GitHubClientMock) PostReviewReply(ctx context.Context, prURL string, reviewCommentID int, body string) error {
	callInfo := struct {
		Ctx             context.Context
		PrURL           string
		ReviewCommentID int
		Body            string
	}{
		Ctx:             ctx,
		PrURL:           prURL,
		ReviewCommentID: reviewCommentID,
		Body:            body,
	}
	mock.lockPostReviewReply.Lock()
	mock.calls.PostReviewReply = append(mock.calls.PostReviewReply, callInfo)
	mock.lockPostReviewReply.Unlock()
	if mock.PostReviewReplyFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PostReviewReplyFunc(ctx, prURL, reviewCommentID, body)
}

// PostReviewReplyCalls gets all the calls that were made to PostReviewReply.
// Check the length with:
//
//	len(mockedClientInterface.PostReviewReplyCalls())
func (mock *GitHubClientMock) PostReviewReplyCalls() []struct {
	Ctx             context.Context
	PrURL           string
	ReviewCommentID int
	Body            string
} {
	var calls []struct {
		Ctx             context.Context
		PrURL           string
		ReviewCommentID int
		Body            string
	}
	mock.lockPostReviewReply.RLock()
	calls = mock.calls.PostReviewReply
	mock.lockPostReviewReply.RUnlock()
	return calls
}

// ResolveReviewThread calls ResolveReviewThreadFunc.
func (mock *GitHubClientMock) ResolveReviewThread(ctx context.Context, prURL string, commentID int) error {
	callInfo := struct {
		Ctx       context.Context
		PrURL     string
		CommentID int
	}{
		Ctx:       ctx,
		PrURL:     prURL,
		CommentID: commentID,
	}
	mock.lockResolveReviewThread.Lock()
	mock.calls.ResolveReviewThread = append(mock.calls.ResolveReviewThread, callInfo)
	mock.lockResolveReviewThread.Unlock()
	if mock.ResolveReviewThreadFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ResolveReviewThreadFunc(ctx, prURL, commentID)
}

// ResolveReviewThreadCalls gets all the calls that were made to ResolveReviewThread.
// Check the length with:
//
//	len(mockedClientInterface.ResolveReviewThreadCalls())
func (mock *GitHubClientMock) ResolveReviewThreadCalls() []struct {
	Ctx       context.Context
	PrURL     string
	CommentID int
} {
	var calls []struct {
		Ctx       context.Context
		PrURL     string
		CommentID int
	}
	mock.lockResolveReviewThread.RLock()
	calls = mock.calls.ResolveReviewThread
	mock.lockResolveReviewThread.RUnlock()
	return calls
}
