// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: migrations.sql

package sqlc

import (
	"context"
)

const createMigrationsTable = `-- name: CreateMigrationsTable :exec
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateMigrationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createMigrationsTable)
	return err
}

const deleteMigration = `-- name: DeleteMigration :exec
DELETE FROM schema_migrations WHERE version = ?
`

func (q *Queries) DeleteMigration(ctx context.Context, version string) error {
	_, err := q.db.ExecContext(ctx, deleteMigration, version)
	return err
}

const getAppliedMigrations = `-- name: GetAppliedMigrations :many
SELECT version FROM schema_migrations
`

func (q *Queries) GetAppliedMigrations(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAppliedMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastMigration = `-- name: GetLastMigration :one
SELECT version FROM schema_migrations
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLastMigration(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastMigration)
	var version string
	err := row.Scan(&version)
	return version, err
}

const listMigrationVersions = `-- name: ListMigrationVersions :many
SELECT version FROM schema_migrations ORDER BY version
`

func (q *Queries) ListMigrationVersions(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMigrationVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMigration = `-- name: RecordMigration :exec
INSERT INTO schema_migrations (version) VALUES (?)
`

func (q *Queries) RecordMigration(ctx context.Context, version string) error {
	_, err := q.db.ExecContext(ctx, recordMigration, version)
	return err
}
