// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Bead struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	Title         sql.NullString `json:"title"`
	PrUrl         sql.NullString `json:"pr_url"`
	ErrorMessage  sql.NullString `json:"error_message"`
	ZellijSession sql.NullString `json:"zellij_session"`
	ZellijPane    sql.NullString `json:"zellij_pane"`
	WorktreePath  sql.NullString `json:"worktree_path"`
	StartedAt     sql.NullTime   `json:"started_at"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type ComplexityCache struct {
	BeadID          string       `json:"bead_id"`
	DescriptionHash string       `json:"description_hash"`
	ComplexityScore int64        `json:"complexity_score"`
	EstimatedTokens int64        `json:"estimated_tokens"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Task struct {
	ID               string         `json:"id"`
	Status           string         `json:"status"`
	TaskType         string         `json:"task_type"`
	ComplexityBudget sql.NullInt64  `json:"complexity_budget"`
	ActualComplexity sql.NullInt64  `json:"actual_complexity"`
	WorkID           sql.NullString `json:"work_id"`
	ZellijSession    sql.NullString `json:"zellij_session"`
	ZellijPane       sql.NullString `json:"zellij_pane"`
	WorktreePath     sql.NullString `json:"worktree_path"`
	PrUrl            sql.NullString `json:"pr_url"`
	ErrorMessage     sql.NullString `json:"error_message"`
	StartedAt        sql.NullTime   `json:"started_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type TaskBead struct {
	TaskID string `json:"task_id"`
	BeadID string `json:"bead_id"`
	Status string `json:"status"`
}

type Work struct {
	ID            string         `json:"id"`
	Status        string         `json:"status"`
	ZellijSession sql.NullString `json:"zellij_session"`
	ZellijTab     sql.NullString `json:"zellij_tab"`
	WorktreePath  sql.NullString `json:"worktree_path"`
	BranchName    sql.NullString `json:"branch_name"`
	BaseBranch    sql.NullString `json:"base_branch"`
	PrUrl         sql.NullString `json:"pr_url"`
	ErrorMessage  sql.NullString `json:"error_message"`
	StartedAt     sql.NullTime   `json:"started_at"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type WorkTask struct {
	WorkID   string        `json:"work_id"`
	TaskID   string        `json:"task_id"`
	Position sql.NullInt64 `json:"position"`
}
