// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CacheComplexity(ctx context.Context, arg CacheComplexityParams) error
	CompleteBead(ctx context.Context, arg CompleteBeadParams) (int64, error)
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (int64, error)
	CompleteTaskBead(ctx context.Context, arg CompleteTaskBeadParams) (int64, error)
	CountEstimatedBeads(ctx context.Context, beadIds []string) (int64, error)
	CountTaskBeadStatuses(ctx context.Context, taskID string) (CountTaskBeadStatusesRow, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateTaskBead(ctx context.Context, arg CreateTaskBeadParams) error
	FailBead(ctx context.Context, arg FailBeadParams) (int64, error)
	FailTask(ctx context.Context, arg FailTaskParams) (int64, error)
	FailTaskBead(ctx context.Context, arg FailTaskBeadParams) (int64, error)
	GetAllCachedComplexity(ctx context.Context) ([]GetAllCachedComplexityRow, error)
	GetBead(ctx context.Context, id string) (Bead, error)
	GetBeadStatus(ctx context.Context, id string) (string, error)
	GetCachedComplexity(ctx context.Context, arg GetCachedComplexityParams) (GetCachedComplexityRow, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetTaskBeads(ctx context.Context, taskID string) ([]string, error)
	GetTaskForBead(ctx context.Context, beadID string) (string, error)
	ListBeads(ctx context.Context) ([]Bead, error)
	ListBeadsByStatus(ctx context.Context, status string) ([]Bead, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByStatus(ctx context.Context, status string) ([]Task, error)
	ResetTaskStatus(ctx context.Context, id string) (int64, error)
	StartBead(ctx context.Context, arg StartBeadParams) error
	StartTask(ctx context.Context, arg StartTaskParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
