// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: workflow_state.sql

package sqlc

import (
	"context"
)

const completeWorkflowStep = `-- name: CompleteWorkflowStep :execrows
UPDATE workflow_state
SET step_status = 'completed',
    updated_at = CURRENT_TIMESTAMP
WHERE work_id = ?
`

func (q *Queries) CompleteWorkflowStep(ctx context.Context, workID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeWorkflowStep, workID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createWorkflowState = `-- name: CreateWorkflowState :exec
INSERT INTO workflow_state (work_id, current_step, step_status, step_data)
VALUES (?, ?, ?, ?)
`

type CreateWorkflowStateParams struct {
	WorkID      string `json:"work_id"`
	CurrentStep int64  `json:"current_step"`
	StepStatus  string `json:"step_status"`
	StepData    string `json:"step_data"`
}

func (q *Queries) CreateWorkflowState(ctx context.Context, arg CreateWorkflowStateParams) error {
	_, err := q.db.ExecContext(ctx, createWorkflowState,
		arg.WorkID,
		arg.CurrentStep,
		arg.StepStatus,
		arg.StepData,
	)
	return err
}

const deleteWorkflowState = `-- name: DeleteWorkflowState :execrows
DELETE FROM workflow_state
WHERE work_id = ?
`

func (q *Queries) DeleteWorkflowState(ctx context.Context, workID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkflowState, workID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failWorkflowStep = `-- name: FailWorkflowStep :execrows
UPDATE workflow_state
SET step_status = 'failed',
    error_message = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE work_id = ?
`

type FailWorkflowStepParams struct {
	ErrorMessage string `json:"error_message"`
	WorkID       string `json:"work_id"`
}

func (q *Queries) FailWorkflowStep(ctx context.Context, arg FailWorkflowStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failWorkflowStep, arg.ErrorMessage, arg.WorkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWorkflowState = `-- name: GetWorkflowState :one
SELECT work_id, current_step, step_status, step_data, error_message, created_at, updated_at
FROM workflow_state
WHERE work_id = ?
`

func (q *Queries) GetWorkflowState(ctx context.Context, workID string) (WorkflowState, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowState, workID)
	var i WorkflowState
	err := row.Scan(
		&i.WorkID,
		&i.CurrentStep,
		&i.StepStatus,
		&i.StepData,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingWorkflows = `-- name: ListPendingWorkflows :many
SELECT work_id, current_step, step_status, step_data, error_message, created_at, updated_at
FROM workflow_state
WHERE step_status = 'pending' OR step_status = 'processing'
ORDER BY created_at
`

func (q *Queries) ListPendingWorkflows(ctx context.Context) ([]WorkflowState, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowState{}
	for rows.Next() {
		var i WorkflowState
		if err := rows.Scan(
			&i.WorkID,
			&i.CurrentStep,
			&i.StepStatus,
			&i.StepData,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowStep = `-- name: UpdateWorkflowStep :execrows
UPDATE workflow_state
SET current_step = ?,
    step_status = ?,
    step_data = ?,
    error_message = '',
    updated_at = CURRENT_TIMESTAMP
WHERE work_id = ?
`

type UpdateWorkflowStepParams struct {
	CurrentStep int64  `json:"current_step"`
	StepStatus  string `json:"step_status"`
	StepData    string `json:"step_data"`
	WorkID      string `json:"work_id"`
}

func (q *Queries) UpdateWorkflowStep(ctx context.Context, arg UpdateWorkflowStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkflowStep,
		arg.CurrentStep,
		arg.StepStatus,
		arg.StepData,
		arg.WorkID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
