// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package process

import (
	"context"
	"sync"
)

// Ensure, that ProcessListerMock does implement ProcessLister.
// If this is not the case, regenerate this file with moq.
var _ ProcessLister = &ProcessListerMock{}

// ProcessListerMock is a mock implementation of ProcessLister.
//
//	func TestSomethingThatUsesProcessLister(t *testing.T) {
//
//		// make and configure a mocked ProcessLister
//		mockedProcessLister := &ProcessListerMock{
//			GetProcessListFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetProcessList method")
//			},
//		}
//
//		// use mockedProcessLister in code that requires ProcessLister
//		// and then make assertions.
//
//	}
type ProcessListerMock struct {
	// GetProcessListFunc mocks the GetProcessList method.
	GetProcessListFunc func(ctx context.Context) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetProcessList holds details about calls to the GetProcessList method.
		GetProcessList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetProcessList sync.RWMutex
}

// GetProcessList calls GetProcessListFunc.
func (mock *ProcessListerMock) GetProcessList(ctx context.Context) ([]string, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetProcessList.Lock()
	mock.calls.GetProcessList = append(mock.calls.GetProcessList, callInfo)
	mock.lockGetProcessList.Unlock()
	if mock.GetProcessListFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.GetProcessListFunc(ctx)
}

// GetProcessListCalls gets all the calls that were made to GetProcessList.
// Check the length with:
//
//	len(mockedProcessLister.GetProcessListCalls())
func (mock *ProcessListerMock) GetProcessListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetProcessList.RLock()
	calls = mock.calls.GetProcessList
	mock.lockGetProcessList.RUnlock()
	return calls
}

// Ensure, that ProcessKillerMock does implement ProcessKiller.
// If this is not the case, regenerate this file with moq.
var _ ProcessKiller = &ProcessKillerMock{}

// ProcessKillerMock is a mock implementation of ProcessKiller.
//
//	func TestSomethingThatUsesProcessKiller(t *testing.T) {
//
//		// make and configure a mocked ProcessKiller
//		mockedProcessKiller := &ProcessKillerMock{
//			KillByPatternFunc: func(ctx context.Context, pattern string) error {
//				panic("mock out the KillByPattern method")
//			},
//		}
//
//		// use mockedProcessKiller in code that requires ProcessKiller
//		// and then make assertions.
//
//	}
type ProcessKillerMock struct {
	// KillByPatternFunc mocks the KillByPattern method.
	KillByPatternFunc func(ctx context.Context, pattern string) error

	// calls tracks calls to the methods.
	calls struct {
		// KillByPattern holds details about calls to the KillByPattern method.
		KillByPattern []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pattern is the pattern argument value.
			Pattern string
		}
	}
	lockKillByPattern sync.RWMutex
}

// KillByPattern calls KillByPatternFunc.
func (mock *ProcessKillerMock) KillByPattern(ctx context.Context, pattern string) error {
	callInfo := struct {
		Ctx     context.Context
		Pattern string
	}{
		Ctx:     ctx,
		Pattern: pattern,
	}
	mock.lockKillByPattern.Lock()
	mock.calls.KillByPattern = append(mock.calls.KillByPattern, callInfo)
	mock.lockKillByPattern.Unlock()
	if mock.KillByPatternFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.KillByPatternFunc(ctx, pattern)
}

// KillByPatternCalls gets all the calls that were made to KillByPattern.
// Check the length with:
//
//	len(mockedProcessKiller.KillByPatternCalls())
func (mock *ProcessKillerMock) KillByPatternCalls() []struct {
	Ctx     context.Context
	Pattern string
} {
	var calls []struct {
		Ctx     context.Context
		Pattern string
	}
	mock.lockKillByPattern.RLock()
	calls = mock.calls.KillByPattern
	mock.lockKillByPattern.RUnlock()
	return calls
}
