// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package task

import (
	"context"
	"github.com/newhook/co/internal/beads"
	"sync"
)

// Ensure, that ComplexityEstimatorMock does implement ComplexityEstimator.
// If this is not the case, regenerate this file with moq.
var _ ComplexityEstimator = &ComplexityEstimatorMock{}

// ComplexityEstimatorMock is a mock implementation of ComplexityEstimator.
//
//	func TestSomethingThatUsesComplexityEstimator(t *testing.T) {
//
//		// make and configure a mocked ComplexityEstimator
//		mockedComplexityEstimator := &ComplexityEstimatorMock{
//			EstimateFunc: func(ctx context.Context, bead beads.Bead) (int, int, error) {
//				panic("mock out the Estimate method")
//			},
//		}
//
//		// use mockedComplexityEstimator in code that requires ComplexityEstimator
//		// and then make assertions.
//
//	}
type ComplexityEstimatorMock struct {
	// EstimateFunc mocks the Estimate method.
	EstimateFunc func(ctx context.Context, bead beads.Bead) (int, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Estimate holds details about calls to the Estimate method.
		Estimate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bead is the bead argument value.
			Bead beads.Bead
		}
	}
	lockEstimate sync.RWMutex
}

// Estimate calls EstimateFunc.
func (mock *ComplexityEstimatorMock) Estimate(ctx context.Context, bead beads.Bead) (int, int, error) {
	callInfo := struct {
		Ctx  context.Context
		Bead beads.Bead
	}{
		Ctx:  ctx,
		Bead: bead,
	}
	mock.lockEstimate.Lock()
	mock.calls.Estimate = append(mock.calls.Estimate, callInfo)
	mock.lockEstimate.Unlock()
	if mock.EstimateFunc == nil {
		var (
			scoreOut  int
			tokensOut int
			errOut    error
		)
		return scoreOut, tokensOut, errOut
	}
	return mock.EstimateFunc(ctx, bead)
}

// EstimateCalls gets all the calls that were made to Estimate.
// Check the length with:
//
//	len(mockedComplexityEstimator.EstimateCalls())
func (mock *ComplexityEstimatorMock) EstimateCalls() []struct {
	Ctx  context.Context
	Bead beads.Bead
} {
	var calls []struct {
		Ctx  context.Context
		Bead beads.Bead
	}
	mock.lockEstimate.RLock()
	calls = mock.calls.Estimate
	mock.lockEstimate.RUnlock()
	return calls
}
