// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package names

import (
	"context"
	"sync"
)

// Ensure, that GeneratorMock does implement Generator.
// If this is not the case, regenerate this file with moq.
var _ Generator = &GeneratorMock{}

// GeneratorMock is a mock implementation of Generator.
//
//	func TestSomethingThatUsesGenerator(t *testing.T) {
//
//		// make and configure a mocked Generator
//		mockedGenerator := &GeneratorMock{
//			GetNextAvailableNameFunc: func(ctx context.Context, db DB) (string, error) {
//				panic("mock out the GetNextAvailableName method")
//			},
//		}
//
//		// use mockedGenerator in code that requires Generator
//		// and then make assertions.
//
//	}
type GeneratorMock struct {
	// GetNextAvailableNameFunc mocks the GetNextAvailableName method.
	GetNextAvailableNameFunc func(ctx context.Context, db DB) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetNextAvailableName holds details about calls to the GetNextAvailableName method.
		GetNextAvailableName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db DB
		}
	}
	lockGetNextAvailableName sync.RWMutex
}

// GetNextAvailableName calls GetNextAvailableNameFunc.
func (mock *GeneratorMock) GetNextAvailableName(ctx context.Context, db DB) (string, error) {
	callInfo := struct {
		Ctx context.Context
		Db  DB
	}{
		Ctx: ctx,
		Db:  db,
	}
	mock.lockGetNextAvailableName.Lock()
	mock.calls.GetNextAvailableName = append(mock.calls.GetNextAvailableName, callInfo)
	mock.lockGetNextAvailableName.Unlock()
	if mock.GetNextAvailableNameFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.GetNextAvailableNameFunc(ctx, db)
}

// GetNextAvailableNameCalls gets all the calls that were made to GetNextAvailableName.
// Check the length with:
//
//	len(mockedGenerator.GetNextAvailableNameCalls())
func (mock *GeneratorMock) GetNextAvailableNameCalls() []struct {
	Ctx context.Context
	Db  DB
} {
	var calls []struct {
		Ctx context.Context
		Db  DB
	}
	mock.lockGetNextAvailableName.RLock()
	calls = mock.calls.GetNextAvailableName
	mock.lockGetNextAvailableName.RUnlock()
	return calls
}
